
///// Automatically generated by makeproxy, don't modify! /////

#ifndef __PPSHBQQYOIMHMSPNDVXZXSJNQXJRISGO__
#define __PPSHBQQYOIMHMSPNDVXZXSJNQXJRISGO__

#include <WinSCard.h>


// Typedefs of the exported symbols

typedef LONG (WINAPI *tSCardEstablishContext) (
    IN  DWORD dwScope,
    IN  LPCVOID pvReserved1,
    IN  LPCVOID pvReserved2,
    OUT LPSCARDCONTEXT phContext);
typedef LONG (WINAPI *tSCardReleaseContext) (
    IN      SCARDCONTEXT hContext);
typedef LONG (WINAPI *tSCardIsValidContext) (
    IN      SCARDCONTEXT hContext);
typedef LONG (WINAPI *tSCardListReaderGroupsA) (
    IN      SCARDCONTEXT hContext,
    OUT     LPSTR mszGroups,
    IN OUT  LPDWORD pcchGroups);
typedef LONG (WINAPI *tSCardListReaderGroupsW) (
    IN      SCARDCONTEXT hContext,
    OUT     LPWSTR mszGroups,
    IN OUT  LPDWORD pcchGroups);
typedef LONG (WINAPI *tSCardListReadersA) (
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR mszGroups,
    OUT     LPSTR mszReaders,
    IN OUT  LPDWORD pcchReaders);
typedef LONG (WINAPI *tSCardListReadersW) (
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR mszGroups,
    OUT     LPWSTR mszReaders,
    IN OUT  LPDWORD pcchReaders);
typedef LONG (WINAPI *tSCardListCardsA) (
    IN      SCARDCONTEXT hContext,
    IN      LPCBYTE pbAtr,
    IN      LPCGUID rgquidInterfaces,
    IN      DWORD cguidInterfaceCount,
    OUT     LPSTR mszCards,
    IN OUT  LPDWORD pcchCards);
typedef LONG (WINAPI *tSCardListCardsW) (
    IN      SCARDCONTEXT hContext,
    IN      LPCBYTE pbAtr,
    IN      LPCGUID rgquidInterfaces,
    IN      DWORD cguidInterfaceCount,
    OUT     LPWSTR mszCards,
    IN OUT  LPDWORD pcchCards);
typedef LONG (WINAPI *tSCardListInterfacesA) (
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR szCard,
    OUT     LPGUID pguidInterfaces,
    IN OUT  LPDWORD pcguidInterfaces);
typedef LONG (WINAPI *tSCardListInterfacesW) (
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR szCard,
    OUT     LPGUID pguidInterfaces,
    IN OUT  LPDWORD pcguidInterfaces);
typedef LONG (WINAPI *tSCardGetProviderIdA) (
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR szCard,
    OUT     LPGUID pguidProviderId);
typedef LONG (WINAPI *tSCardGetProviderIdW) (
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR szCard,
    OUT     LPGUID pguidProviderId);
typedef LONG (WINAPI *tSCardGetCardTypeProviderNameA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szCardName,
    IN DWORD dwProviderId,
    OUT LPSTR szProvider,
    IN OUT LPDWORD pcchProvider);
typedef LONG (WINAPI *tSCardGetCardTypeProviderNameW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szCardName,
    IN DWORD dwProviderId,
    OUT LPWSTR szProvider,
    IN OUT LPDWORD pcchProvider);
typedef LONG (WINAPI *tSCardIntroduceReaderGroupA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szGroupName);
typedef LONG (WINAPI *tSCardIntroduceReaderGroupW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szGroupName);
typedef LONG (WINAPI *tSCardForgetReaderGroupA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szGroupName);
typedef LONG (WINAPI *tSCardForgetReaderGroupW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szGroupName);
typedef LONG (WINAPI *tSCardIntroduceReaderA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szReaderName,
    IN LPCSTR szDeviceName);
typedef LONG (WINAPI *tSCardIntroduceReaderW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szReaderName,
    IN LPCWSTR szDeviceName);
typedef LONG (WINAPI *tSCardForgetReaderA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szReaderName);
typedef LONG (WINAPI *tSCardForgetReaderW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szReaderName);
typedef LONG (WINAPI *tSCardAddReaderToGroupA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szReaderName,
    IN LPCSTR szGroupName);
typedef LONG (WINAPI *tSCardAddReaderToGroupW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szReaderName,
    IN LPCWSTR szGroupName);
typedef LONG (WINAPI *tSCardRemoveReaderFromGroupA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szReaderName,
    IN LPCSTR szGroupName);
typedef LONG (WINAPI *tSCardRemoveReaderFromGroupW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szReaderName,
    IN LPCWSTR szGroupName);
typedef LONG (WINAPI *tSCardIntroduceCardTypeA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szCardName,
    IN LPCGUID pguidPrimaryProvider,
    IN LPCGUID rgguidInterfaces,
    IN DWORD dwInterfaceCount,
    IN LPCBYTE pbAtr,
    IN LPCBYTE pbAtrMask,
    IN DWORD cbAtrLen);
typedef LONG (WINAPI *tSCardIntroduceCardTypeW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szCardName,
    IN LPCGUID pguidPrimaryProvider,
    IN LPCGUID rgguidInterfaces,
    IN DWORD dwInterfaceCount,
    IN LPCBYTE pbAtr,
    IN LPCBYTE pbAtrMask,
    IN DWORD cbAtrLen);
typedef LONG (WINAPI *tSCardSetCardTypeProviderNameA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szCardName,
    IN DWORD dwProviderId,
    IN LPCSTR szProvider);
typedef LONG (WINAPI *tSCardSetCardTypeProviderNameW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szCardName,
    IN DWORD dwProviderId,
    IN LPCWSTR szProvider);
typedef LONG (WINAPI *tSCardForgetCardTypeA) (
    IN SCARDCONTEXT hContext,
    IN LPCSTR szCardName);
typedef LONG (WINAPI *tSCardForgetCardTypeW) (
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szCardName);
typedef LONG (WINAPI *tSCardFreeMemory) (
    IN SCARDCONTEXT hContext,
    IN LPCVOID pvMem);
typedef HANDLE (WINAPI *tSCardAccessStartedEvent) (void);
typedef void (WINAPI *tSCardReleaseStartedEvent) (void);
typedef LONG (WINAPI *tSCardLocateCardsA) (
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR mszCards,
    IN OUT  LPSCARD_READERSTATEA rgReaderStates,
    IN      DWORD cReaders);
typedef LONG (WINAPI *tSCardLocateCardsW) (
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR mszCards,
    IN OUT  LPSCARD_READERSTATEW rgReaderStates,
    IN      DWORD cReaders);
typedef LONG (WINAPI *tSCardLocateCardsByATRA) (
    IN      SCARDCONTEXT hContext,
    IN      LPSCARD_ATRMASK rgAtrMasks,
    IN      DWORD cAtrs,
    IN OUT  LPSCARD_READERSTATEA rgReaderStates,
    IN      DWORD cReaders);
typedef LONG (WINAPI *tSCardLocateCardsByATRW) (
    IN      SCARDCONTEXT hContext,
    IN      LPSCARD_ATRMASK rgAtrMasks,
    IN      DWORD cAtrs,
    IN OUT  LPSCARD_READERSTATEW rgReaderStates,
    IN      DWORD cReaders);
typedef LONG (WINAPI *tSCardGetStatusChangeA) (
    IN      SCARDCONTEXT hContext,
    IN      DWORD dwTimeout,
    IN OUT  LPSCARD_READERSTATEA rgReaderStates,
    IN      DWORD cReaders);
typedef LONG (WINAPI *tSCardGetStatusChangeW) (
    IN      SCARDCONTEXT hContext,
    IN      DWORD dwTimeout,
    IN OUT  LPSCARD_READERSTATEW rgReaderStates,
    IN      DWORD cReaders);
typedef LONG (WINAPI *tSCardCancel) (
    IN      SCARDCONTEXT hContext);
typedef LONG (WINAPI *tSCardConnectA) (
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR szReader,
    IN      DWORD dwShareMode,
    IN      DWORD dwPreferredProtocols,
    OUT     LPSCARDHANDLE phCard,
    OUT     LPDWORD pdwActiveProtocol);
typedef LONG (WINAPI *tSCardConnectW) (
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR szReader,
    IN      DWORD dwShareMode,
    IN      DWORD dwPreferredProtocols,
    OUT     LPSCARDHANDLE phCard,
    OUT     LPDWORD pdwActiveProtocol);
typedef LONG (WINAPI *tSCardReconnect) (
    IN      SCARDHANDLE hCard,
    IN      DWORD dwShareMode,
    IN      DWORD dwPreferredProtocols,
    IN      DWORD dwInitialization,
    OUT     LPDWORD pdwActiveProtocol);
typedef LONG (WINAPI *tSCardDisconnect) (
    IN      SCARDHANDLE hCard,
    IN      DWORD dwDisposition);
typedef LONG (WINAPI *tSCardBeginTransaction) (
    IN      SCARDHANDLE hCard);
typedef LONG (WINAPI *tSCardEndTransaction) (
    IN      SCARDHANDLE hCard,
    IN      DWORD dwDisposition);
typedef LONG (WINAPI *tSCardCancelTransaction) (
    IN      SCARDHANDLE hCard);
typedef LONG (WINAPI *tSCardState) (
    IN SCARDHANDLE hCard,
    OUT LPDWORD pdwState,
    OUT LPDWORD pdwProtocol,
    OUT LPBYTE pbAtr,
    IN OUT LPDWORD pcbAtrLen);
typedef LONG (WINAPI *tSCardStatusA) (
    IN SCARDHANDLE hCard,
    OUT LPSTR szReaderName,
    IN OUT LPDWORD pcchReaderLen,
    OUT LPDWORD pdwState,
    OUT LPDWORD pdwProtocol,
    OUT LPBYTE pbAtr,
    IN OUT LPDWORD pcbAtrLen);
typedef LONG (WINAPI *tSCardStatusW) (
    IN SCARDHANDLE hCard,
    OUT LPWSTR szReaderName,
    IN OUT LPDWORD pcchReaderLen,
    OUT LPDWORD pdwState,
    OUT LPDWORD pdwProtocol,
    OUT LPBYTE pbAtr,
    IN OUT LPDWORD pcbAtrLen);
typedef LONG (WINAPI *tSCardTransmit) (
    IN SCARDHANDLE hCard,
    IN LPCSCARD_IO_REQUEST pioSendPci,
    IN LPCBYTE pbSendBuffer,
    IN DWORD cbSendLength,
    IN OUT LPSCARD_IO_REQUEST pioRecvPci,
    OUT LPBYTE pbRecvBuffer,
    IN OUT LPDWORD pcbRecvLength);
typedef LONG (WINAPI *tSCardGetTransmitCount) (
    IN SCARDHANDLE hCard,
    OUT LPDWORD pcTransmitCount);
typedef LONG (WINAPI *tSCardControl) (
    IN      SCARDHANDLE hCard,
    IN      DWORD dwControlCode,
    IN      LPCVOID lpInBuffer,
    IN      DWORD nInBufferSize,
    OUT     LPVOID lpOutBuffer,
    IN      DWORD nOutBufferSize,
    OUT     LPDWORD lpBytesReturned);
typedef LONG (WINAPI *tSCardGetAttrib) (
    IN SCARDHANDLE hCard,
    IN DWORD dwAttrId,
    OUT LPBYTE pbAttr,
    IN OUT LPDWORD pcbAttrLen);
typedef LONG (WINAPI *tSCardSetAttrib) (
    IN SCARDHANDLE hCard,
    IN DWORD dwAttrId,
    IN LPCBYTE pbAttr,
    IN DWORD cbAttrLen);
typedef LONG (WINAPI *tSCardUIDlgSelectCardA) (
    LPOPENCARDNAMEA_EX);
typedef LONG (WINAPI *tSCardUIDlgSelectCardW) (
    LPOPENCARDNAMEW_EX);
typedef LONG (WINAPI *tGetOpenCardNameA) (
    LPOPENCARDNAMEA);
typedef LONG (WINAPI *tGetOpenCardNameW) (
    LPOPENCARDNAMEW);
typedef LONG (WINAPI *tSCardDlgExtendedError) (void);
typedef LONG (WINAPI *tSCardReadCacheA) (
    IN SCARDCONTEXT hContext,
    IN UUID * CardIdentifier,
    IN DWORD FreshnessCounter,
    IN LPSTR LookupName,
    OUT PBYTE Data,
    OUT DWORD * DataLen);
typedef LONG (WINAPI *tSCardReadCacheW) (
    IN SCARDCONTEXT hContext,
    IN UUID * CardIdentifier,
    IN DWORD FreshnessCounter,
    IN LPWSTR LookupName,
    OUT PBYTE Data,
    OUT DWORD * DataLen);
typedef LONG (WINAPI *tSCardWriteCacheA) (
    IN SCARDCONTEXT hContext,
    IN UUID * CardIdentifier,
    IN DWORD FreshnessCounter,
    IN LPSTR LookupName,
    IN PBYTE Data,
    IN DWORD DataLen);
typedef LONG (WINAPI *tSCardWriteCacheW) (
    IN SCARDCONTEXT hContext,
    IN UUID * CardIdentifier,
    IN DWORD FreshnessCounter,
    IN LPWSTR LookupName,
    IN PBYTE Data,
    IN DWORD DataLen);

// Pointers to the functions in the lib to be proxy-ed

extern tSCardEstablishContext pSCardEstablishContext;
extern tSCardReleaseContext pSCardReleaseContext;
extern tSCardIsValidContext pSCardIsValidContext;
extern tSCardListReaderGroupsA pSCardListReaderGroupsA;
extern tSCardListReaderGroupsW pSCardListReaderGroupsW;
extern tSCardListReadersA pSCardListReadersA;
extern tSCardListReadersW pSCardListReadersW;
extern tSCardListCardsA pSCardListCardsA;
extern tSCardListCardsW pSCardListCardsW;
extern tSCardListInterfacesA pSCardListInterfacesA;
extern tSCardListInterfacesW pSCardListInterfacesW;
extern tSCardGetProviderIdA pSCardGetProviderIdA;
extern tSCardGetProviderIdW pSCardGetProviderIdW;
extern tSCardGetCardTypeProviderNameA pSCardGetCardTypeProviderNameA;
extern tSCardGetCardTypeProviderNameW pSCardGetCardTypeProviderNameW;
extern tSCardIntroduceReaderGroupA pSCardIntroduceReaderGroupA;
extern tSCardIntroduceReaderGroupW pSCardIntroduceReaderGroupW;
extern tSCardForgetReaderGroupA pSCardForgetReaderGroupA;
extern tSCardForgetReaderGroupW pSCardForgetReaderGroupW;
extern tSCardIntroduceReaderA pSCardIntroduceReaderA;
extern tSCardIntroduceReaderW pSCardIntroduceReaderW;
extern tSCardForgetReaderA pSCardForgetReaderA;
extern tSCardForgetReaderW pSCardForgetReaderW;
extern tSCardAddReaderToGroupA pSCardAddReaderToGroupA;
extern tSCardAddReaderToGroupW pSCardAddReaderToGroupW;
extern tSCardRemoveReaderFromGroupA pSCardRemoveReaderFromGroupA;
extern tSCardRemoveReaderFromGroupW pSCardRemoveReaderFromGroupW;
extern tSCardIntroduceCardTypeA pSCardIntroduceCardTypeA;
extern tSCardIntroduceCardTypeW pSCardIntroduceCardTypeW;
extern tSCardSetCardTypeProviderNameA pSCardSetCardTypeProviderNameA;
extern tSCardSetCardTypeProviderNameW pSCardSetCardTypeProviderNameW;
extern tSCardForgetCardTypeA pSCardForgetCardTypeA;
extern tSCardForgetCardTypeW pSCardForgetCardTypeW;
extern tSCardFreeMemory pSCardFreeMemory;
extern tSCardAccessStartedEvent pSCardAccessStartedEvent;
extern tSCardReleaseStartedEvent pSCardReleaseStartedEvent;
extern tSCardLocateCardsA pSCardLocateCardsA;
extern tSCardLocateCardsW pSCardLocateCardsW;
extern tSCardLocateCardsByATRA pSCardLocateCardsByATRA;
extern tSCardLocateCardsByATRW pSCardLocateCardsByATRW;
extern tSCardGetStatusChangeA pSCardGetStatusChangeA;
extern tSCardGetStatusChangeW pSCardGetStatusChangeW;
extern tSCardCancel pSCardCancel;
extern tSCardConnectA pSCardConnectA;
extern tSCardConnectW pSCardConnectW;
extern tSCardReconnect pSCardReconnect;
extern tSCardDisconnect pSCardDisconnect;
extern tSCardBeginTransaction pSCardBeginTransaction;
extern tSCardEndTransaction pSCardEndTransaction;
extern tSCardCancelTransaction pSCardCancelTransaction;
extern tSCardState pSCardState;
extern tSCardStatusA pSCardStatusA;
extern tSCardStatusW pSCardStatusW;
extern tSCardTransmit pSCardTransmit;
extern tSCardGetTransmitCount pSCardGetTransmitCount;
extern tSCardControl pSCardControl;
extern tSCardGetAttrib pSCardGetAttrib;
extern tSCardSetAttrib pSCardSetAttrib;
extern tSCardUIDlgSelectCardA pSCardUIDlgSelectCardA;
extern tSCardUIDlgSelectCardW pSCardUIDlgSelectCardW;
extern tGetOpenCardNameA pGetOpenCardNameA;
extern tGetOpenCardNameW pGetOpenCardNameW;
extern tSCardDlgExtendedError pSCardDlgExtendedError;
extern tSCardReadCacheA pSCardReadCacheA;
extern tSCardReadCacheW pSCardReadCacheW;
extern tSCardWriteCacheA pSCardWriteCacheA;
extern tSCardWriteCacheW pSCardWriteCacheW;

// Declarations of the proxy functions

WINSCARDAPI LONG WINAPI imp_SCardEstablishContext(
    IN  DWORD dwScope,
    IN  LPCVOID pvReserved1,
    IN  LPCVOID pvReserved2,
    OUT LPSCARDCONTEXT phContext);
WINSCARDAPI LONG WINAPI imp_SCardReleaseContext(
    IN      SCARDCONTEXT hContext);
WINSCARDAPI LONG WINAPI imp_SCardIsValidContext(
    IN      SCARDCONTEXT hContext);
WINSCARDAPI LONG WINAPI imp_SCardListReaderGroupsA(
    IN      SCARDCONTEXT hContext,
    OUT     LPSTR mszGroups,
    IN OUT  LPDWORD pcchGroups);
WINSCARDAPI LONG WINAPI imp_SCardListReaderGroupsW(
    IN      SCARDCONTEXT hContext,
    OUT     LPWSTR mszGroups,
    IN OUT  LPDWORD pcchGroups);
WINSCARDAPI LONG WINAPI imp_SCardListReadersA(
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR mszGroups,
    OUT     LPSTR mszReaders,
    IN OUT  LPDWORD pcchReaders);
WINSCARDAPI LONG WINAPI imp_SCardListReadersW(
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR mszGroups,
    OUT     LPWSTR mszReaders,
    IN OUT  LPDWORD pcchReaders);
WINSCARDAPI LONG WINAPI imp_SCardListCardsA(
    IN      SCARDCONTEXT hContext,
    IN      LPCBYTE pbAtr,
    IN      LPCGUID rgquidInterfaces,
    IN      DWORD cguidInterfaceCount,
    OUT     LPSTR mszCards,
    IN OUT  LPDWORD pcchCards);
WINSCARDAPI LONG WINAPI imp_SCardListCardsW(
    IN      SCARDCONTEXT hContext,
    IN      LPCBYTE pbAtr,
    IN      LPCGUID rgquidInterfaces,
    IN      DWORD cguidInterfaceCount,
    OUT     LPWSTR mszCards,
    IN OUT  LPDWORD pcchCards);
WINSCARDAPI LONG WINAPI imp_SCardListInterfacesA(
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR szCard,
    OUT     LPGUID pguidInterfaces,
    IN OUT  LPDWORD pcguidInterfaces);
WINSCARDAPI LONG WINAPI imp_SCardListInterfacesW(
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR szCard,
    OUT     LPGUID pguidInterfaces,
    IN OUT  LPDWORD pcguidInterfaces);
WINSCARDAPI LONG WINAPI imp_SCardGetProviderIdA(
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR szCard,
    OUT     LPGUID pguidProviderId);
WINSCARDAPI LONG WINAPI imp_SCardGetProviderIdW(
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR szCard,
    OUT     LPGUID pguidProviderId);
WINSCARDAPI LONG WINAPI imp_SCardGetCardTypeProviderNameA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szCardName,
    IN DWORD dwProviderId,
    OUT LPSTR szProvider,
    IN OUT LPDWORD pcchProvider);
WINSCARDAPI LONG WINAPI imp_SCardGetCardTypeProviderNameW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szCardName,
    IN DWORD dwProviderId,
    OUT LPWSTR szProvider,
    IN OUT LPDWORD pcchProvider);
WINSCARDAPI LONG WINAPI imp_SCardIntroduceReaderGroupA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szGroupName);
WINSCARDAPI LONG WINAPI imp_SCardIntroduceReaderGroupW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szGroupName);
WINSCARDAPI LONG WINAPI imp_SCardForgetReaderGroupA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szGroupName);
WINSCARDAPI LONG WINAPI imp_SCardForgetReaderGroupW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szGroupName);
WINSCARDAPI LONG WINAPI imp_SCardIntroduceReaderA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szReaderName,
    IN LPCSTR szDeviceName);
WINSCARDAPI LONG WINAPI imp_SCardIntroduceReaderW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szReaderName,
    IN LPCWSTR szDeviceName);
WINSCARDAPI LONG WINAPI imp_SCardForgetReaderA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szReaderName);
WINSCARDAPI LONG WINAPI imp_SCardForgetReaderW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szReaderName);
WINSCARDAPI LONG WINAPI imp_SCardAddReaderToGroupA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szReaderName,
    IN LPCSTR szGroupName);
WINSCARDAPI LONG WINAPI imp_SCardAddReaderToGroupW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szReaderName,
    IN LPCWSTR szGroupName);
WINSCARDAPI LONG WINAPI imp_SCardRemoveReaderFromGroupA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szReaderName,
    IN LPCSTR szGroupName);
WINSCARDAPI LONG WINAPI imp_SCardRemoveReaderFromGroupW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szReaderName,
    IN LPCWSTR szGroupName);
WINSCARDAPI LONG WINAPI imp_SCardIntroduceCardTypeA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szCardName,
    IN LPCGUID pguidPrimaryProvider,
    IN LPCGUID rgguidInterfaces,
    IN DWORD dwInterfaceCount,
    IN LPCBYTE pbAtr,
    IN LPCBYTE pbAtrMask,
    IN DWORD cbAtrLen);
WINSCARDAPI LONG WINAPI imp_SCardIntroduceCardTypeW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szCardName,
    IN LPCGUID pguidPrimaryProvider,
    IN LPCGUID rgguidInterfaces,
    IN DWORD dwInterfaceCount,
    IN LPCBYTE pbAtr,
    IN LPCBYTE pbAtrMask,
    IN DWORD cbAtrLen);
WINSCARDAPI LONG WINAPI imp_SCardSetCardTypeProviderNameA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szCardName,
    IN DWORD dwProviderId,
    IN LPCSTR szProvider);
WINSCARDAPI LONG WINAPI imp_SCardSetCardTypeProviderNameW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szCardName,
    IN DWORD dwProviderId,
    IN LPCWSTR szProvider);
WINSCARDAPI LONG WINAPI imp_SCardForgetCardTypeA(
    IN SCARDCONTEXT hContext,
    IN LPCSTR szCardName);
WINSCARDAPI LONG WINAPI imp_SCardForgetCardTypeW(
    IN SCARDCONTEXT hContext,
    IN LPCWSTR szCardName);
WINSCARDAPI LONG WINAPI imp_SCardFreeMemory(
    IN SCARDCONTEXT hContext,
    IN LPCVOID pvMem);
WINSCARDAPI HANDLE WINAPI imp_SCardAccessStartedEvent(void);
WINSCARDAPI void WINAPI imp_SCardReleaseStartedEvent(void);
WINSCARDAPI LONG WINAPI imp_SCardLocateCardsA(
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR mszCards,
    IN OUT  LPSCARD_READERSTATEA rgReaderStates,
    IN      DWORD cReaders);
WINSCARDAPI LONG WINAPI imp_SCardLocateCardsW(
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR mszCards,
    IN OUT  LPSCARD_READERSTATEW rgReaderStates,
    IN      DWORD cReaders);
WINSCARDAPI LONG WINAPI imp_SCardLocateCardsByATRA(
    IN      SCARDCONTEXT hContext,
    IN      LPSCARD_ATRMASK rgAtrMasks,
    IN      DWORD cAtrs,
    IN OUT  LPSCARD_READERSTATEA rgReaderStates,
    IN      DWORD cReaders);
WINSCARDAPI LONG WINAPI imp_SCardLocateCardsByATRW(
    IN      SCARDCONTEXT hContext,
    IN      LPSCARD_ATRMASK rgAtrMasks,
    IN      DWORD cAtrs,
    IN OUT  LPSCARD_READERSTATEW rgReaderStates,
    IN      DWORD cReaders);
WINSCARDAPI LONG WINAPI imp_SCardGetStatusChangeA(
    IN      SCARDCONTEXT hContext,
    IN      DWORD dwTimeout,
    IN OUT  LPSCARD_READERSTATEA rgReaderStates,
    IN      DWORD cReaders);
WINSCARDAPI LONG WINAPI imp_SCardGetStatusChangeW(
    IN      SCARDCONTEXT hContext,
    IN      DWORD dwTimeout,
    IN OUT  LPSCARD_READERSTATEW rgReaderStates,
    IN      DWORD cReaders);
WINSCARDAPI LONG WINAPI imp_SCardCancel(
    IN      SCARDCONTEXT hContext);
WINSCARDAPI LONG WINAPI imp_SCardConnectA(
    IN      SCARDCONTEXT hContext,
    IN      LPCSTR szReader,
    IN      DWORD dwShareMode,
    IN      DWORD dwPreferredProtocols,
    OUT     LPSCARDHANDLE phCard,
    OUT     LPDWORD pdwActiveProtocol);
WINSCARDAPI LONG WINAPI imp_SCardConnectW(
    IN      SCARDCONTEXT hContext,
    IN      LPCWSTR szReader,
    IN      DWORD dwShareMode,
    IN      DWORD dwPreferredProtocols,
    OUT     LPSCARDHANDLE phCard,
    OUT     LPDWORD pdwActiveProtocol);
WINSCARDAPI LONG WINAPI imp_SCardReconnect(
    IN      SCARDHANDLE hCard,
    IN      DWORD dwShareMode,
    IN      DWORD dwPreferredProtocols,
    IN      DWORD dwInitialization,
    OUT     LPDWORD pdwActiveProtocol);
WINSCARDAPI LONG WINAPI imp_SCardDisconnect(
    IN      SCARDHANDLE hCard,
    IN      DWORD dwDisposition);
WINSCARDAPI LONG WINAPI imp_SCardBeginTransaction(
    IN      SCARDHANDLE hCard);
WINSCARDAPI LONG WINAPI imp_SCardEndTransaction(
    IN      SCARDHANDLE hCard,
    IN      DWORD dwDisposition);
WINSCARDAPI LONG WINAPI imp_SCardCancelTransaction(
    IN      SCARDHANDLE hCard);
WINSCARDAPI LONG WINAPI imp_SCardState(
    IN SCARDHANDLE hCard,
    OUT LPDWORD pdwState,
    OUT LPDWORD pdwProtocol,
    OUT LPBYTE pbAtr,
    IN OUT LPDWORD pcbAtrLen);
WINSCARDAPI LONG WINAPI imp_SCardStatusA(
    IN SCARDHANDLE hCard,
    OUT LPSTR szReaderName,
    IN OUT LPDWORD pcchReaderLen,
    OUT LPDWORD pdwState,
    OUT LPDWORD pdwProtocol,
    OUT LPBYTE pbAtr,
    IN OUT LPDWORD pcbAtrLen);
WINSCARDAPI LONG WINAPI imp_SCardStatusW(
    IN SCARDHANDLE hCard,
    OUT LPWSTR szReaderName,
    IN OUT LPDWORD pcchReaderLen,
    OUT LPDWORD pdwState,
    OUT LPDWORD pdwProtocol,
    OUT LPBYTE pbAtr,
    IN OUT LPDWORD pcbAtrLen);
WINSCARDAPI LONG WINAPI imp_SCardTransmit(
    IN SCARDHANDLE hCard,
    IN LPCSCARD_IO_REQUEST pioSendPci,
    IN LPCBYTE pbSendBuffer,
    IN DWORD cbSendLength,
    IN OUT LPSCARD_IO_REQUEST pioRecvPci,
    OUT LPBYTE pbRecvBuffer,
    IN OUT LPDWORD pcbRecvLength);
WINSCARDAPI LONG WINAPI imp_SCardGetTransmitCount(
    IN SCARDHANDLE hCard,
    OUT LPDWORD pcTransmitCount);
WINSCARDAPI LONG WINAPI imp_SCardControl(
    IN      SCARDHANDLE hCard,
    IN      DWORD dwControlCode,
    IN      LPCVOID lpInBuffer,
    IN      DWORD nInBufferSize,
    OUT     LPVOID lpOutBuffer,
    IN      DWORD nOutBufferSize,
    OUT     LPDWORD lpBytesReturned);
WINSCARDAPI LONG WINAPI imp_SCardGetAttrib(
    IN SCARDHANDLE hCard,
    IN DWORD dwAttrId,
    OUT LPBYTE pbAttr,
    IN OUT LPDWORD pcbAttrLen);
WINSCARDAPI LONG WINAPI imp_SCardSetAttrib(
    IN SCARDHANDLE hCard,
    IN DWORD dwAttrId,
    IN LPCBYTE pbAttr,
    IN DWORD cbAttrLen);
WINSCARDAPI LONG WINAPI imp_SCardUIDlgSelectCardA(
    LPOPENCARDNAMEA_EX);
WINSCARDAPI LONG WINAPI imp_SCardUIDlgSelectCardW(
    LPOPENCARDNAMEW_EX);
WINSCARDAPI LONG WINAPI imp_GetOpenCardNameA(
    LPOPENCARDNAMEA);
WINSCARDAPI LONG WINAPI imp_GetOpenCardNameW(
    LPOPENCARDNAMEW);
WINSCARDAPI LONG WINAPI imp_SCardDlgExtendedError(void);
WINSCARDAPI LONG WINAPI imp_SCardReadCacheA(
    IN SCARDCONTEXT hContext,
    IN UUID * CardIdentifier,
    IN DWORD FreshnessCounter,
    IN LPSTR LookupName,
    OUT PBYTE Data,
    OUT DWORD * DataLen);
WINSCARDAPI LONG WINAPI imp_SCardReadCacheW(
    IN SCARDCONTEXT hContext,
    IN UUID * CardIdentifier,
    IN DWORD FreshnessCounter,
    IN LPWSTR LookupName,
    OUT PBYTE Data,
    OUT DWORD * DataLen);
WINSCARDAPI LONG WINAPI imp_SCardWriteCacheA(
    IN SCARDCONTEXT hContext,
    IN UUID * CardIdentifier,
    IN DWORD FreshnessCounter,
    IN LPSTR LookupName,
    IN PBYTE Data,
    IN DWORD DataLen);
WINSCARDAPI LONG WINAPI imp_SCardWriteCacheW(
    IN SCARDCONTEXT hContext,
    IN UUID * CardIdentifier,
    IN DWORD FreshnessCounter,
    IN LPWSTR LookupName,
    IN PBYTE Data,
    IN DWORD DataLen);

#endif  // __PPSHBQQYOIMHMSPNDVXZXSJNQXJRISGO__
